# Generated by Django 3.2.9 on 2022-04-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adrees',
            new_name='Address',
        ),
    ]
