# Generated by Django 3.2.9 on 2022-04-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_adrees_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
